FROM docksal/cli:2.6-php7.2

# Install grpc extension for PHP
#RUN set -xe; \
#    apt-get update; \
#	apt install -y build-essential libprotobuf-dev libboost-dev openssl protobuf-compiler; \
##	apt install -y php7.2-cli php7.2-dev php7.2-mysql php7.2-pdo php7.2-xml; \
#	pecl install mysql_xdevapi; \
#	docker-php-ext-enable mysql_xdevapi