#!/usr/bin/env bash

## Run project's Behat tests.
##
## Usage: fin behat [--path=path] [arguments]
##
## path defaults to tests/behat

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

params=''
path='tests'
for i in "$@"; do
	case "$i" in
		--path=*)
			path="${i#*=}"
			;;
		*)
			params="$params$i "
			;;
	esac;
done

behat_yml_path="$PROJECT_ROOT/$path/behat.yml"
if [[ ! -f "$behat_yml_path" ]]; then
	echo "Could not find $behat_yml_path"
	exit 1
fi

cd $PROJECT_ROOT
# Launch Behat tests
fin exec "cd $path && ../vendor/bin/behat $params"