#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin xdebug 1 or fin xdebug 0

# Abort if anything fails
set -e

#-------------------------- Execution --------------------------------

fin config set --env=local XDEBUG_ENABLED=$@
fin project start
fin exec php -v | grep -i xdebug

#-------------------------- END: Execution --------------------------------
